### ISSUE TITLE
Error with git hooks install

### ISSUE THREAD

**Issue by brandonkal** [rycus86/githooks#10]
I noticed `git hooks install` failed.

The current machine state is not ideal. I need to find a better way to handle git upgrades and templates. Current machine state:
```
$ git config --get init.templateDir
/usr/local/Cellar/git/2.19.1/share/git-core/templates
```
That folder no longer exists due to a homebrew update:
```
$ brew --prefix git
/usr/local/opt/git
$ ls -l $(brew --prefix git)
lrwxr-xr-x  1 brandon  admin  20 Mar  2 03:10 /usr/local/opt/git -> ../Cellar/git/2.21.0
```

In a fresh git repo (which doesn't have the githooks templates due to the issue above.
```
$ git hooks install
...
All done! Enjoy!

Please support the project by starring the project at https://github.com/rycus86/githooks, and report bugs or missing features or improvements as issues. Thanks!
/Users/brandon/.githooks/bin/githooks: line 1974: shared_hook_repos: command not found
/Users/brandon/.githooks/bin/githooks: line 1975: syntax error near unexpected token `;;'
/Users/brandon/.githooks/bin/githooks: line 1975: `        ;;'
```

**Comment by rycus86** [comment]
Thanks, that looks interesting. :)
I'll try to have a look over the weekend.

**Comment by rycus86** [comment]
Thanks again for reporting this!
Judging by the output, this may have been some files getting overwritten under the running shell, as there's nothing like the things mentioned in the error message going on around those lines and the referenced function does not exist.

For the actual installation problem, I'd try a `git hooks install --global` or just run the installation without the alias to get the templates installed again. Odd that brew doesn't bring the previous Git template configs on update with it.

Let me know if you think there's more to do on this please! Thanks!

**Comment by brandonkal** [comment]
Thanks for looking into this. I suspect you are right about the errors being specific to my shell being in a broken install state, so I'll go ahead and close this.

Yes, I would have expected brew to carry over the templates on update. I have ince done a fresh install with them in `~/.githooks/templates`. This would be worth briefly mentioning in the README so it doesn't bite anyone else.
