### ISSUE TITLE
Custom install dir.

### ISSUE THREAD

**Issue by gabyx** [rycus86/githooks#12]
It woule be nice if we can adjust the custom install dir over the command-line for `install.sh`
Default ist `$HOME/.githooks`.
Infere the install dir from `git config --global --get alias.hooks` inside.

**Comment by rycus86** [comment]
Sounds like a good idea, thanks for the suggestion!

**Comment by rycus86** [comment]
Had a look at this, it looks like it would need some changes in quite a few changes, so first I'd like to understand if this is something you'd need or a nice to have?
The nice thing about the home folder is that it's (usually) writable by the current user, and it's a convention to store configuration files or folders like this there.

**Comment by rycus86** [comment]
Are you happy to have this closed?

**Comment by gabyx** [comment]
Jeah close it.
