### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by gabyx** [rycus86/githooks#123]
I recently had a conversation with someone who needed assistance with setting up hooks on gitea: I thought about sharing his feedback with all of the contributors here:

>We were finally able to set up our workflow as below:
> 1) Create a repository just for server side hooks (hooks-repo)
> 2) Actual codebase repo (source-code-repo) with only client side hooks. In the server, I used git hooks shared --local <hooks-repo url> on the bare repo.
> 3) As a part of the pre-receive hook on the hooks repo, we are running the "git hooks shared update" command
> Everything worked like a breeze. This library is awesome and thanks for contributing/maintaining it. 
> Do let me know if I can contribute in any way.
>
>Thanks and Regards,
> Nithin Gunasekaran.

**Comment by gabyx** [comment]
@Nithin Gunasekaran: thanks for the compliment and great that it worked out for gitea.

- I was just thinking about extending the server dok with respect to gitea (since gitea does some akward things like overwriting hooks in `.git/hooks` and basically placing the installed `githooks` runner script into a e.g. `pre-receive.d` folder which means the manager runs after the gitea hooks etc...). I will let you know when I maybe have time to do this.

- Actually we have never tested a setup to run `git hooks shared update` when executing a hook. :-P. Good that it works, it will just `git clone/pull` the shared hooks which are configured for this repo. I think you are running  `git hooks shared upadate` on the pre-receive hook in the **codebase repo** (not in the hooks repo) on the server, otherwise I dont understand how it should work :-)?

**Comment by nithin001** [comment]
@gabyx, since both the repositories resided in the same server, it worked for us. The intention was to not have any server side hooks configured on the code-base-repo. It's great that you already have a PR solves that issue as well!

**Comment by gabyx** [comment]
Ah, because you directly use a local path right? something like `git hooks shared --local /data/git/repositories/hooks.git`

**Comment by gabyx** [comment]
@nithin001 See latest changes and `githooks.sharedHooksUpdateTriggers` you can set.
