### ISSUE TITLE
Rewritting in Go

### ISSUE THREAD

**Issue by gabyx** [rycus86/githooks#126]
I am just leaving this for brainstorming:
I am really thinking (since implementing changes in Shell is so much pain in the ass, not even talking about global variables, IFS= etc...) that this project, as it its well testet and setup, would profit from a Go implementation which reduces code size largely.  I am not sure if its worth taking on this endeavour, but I could dive into Go which I anyway wanted to do once in a while. 

If there is support from others to do this, maybe why not give it a shot :-), takes probably some time.
I have just seen as a contributor of several PRs here, that it gets more and more messy and also cumbersome in Shell. If 

The progress of porting this application could be like this:
- [x] Make a Go project
- [ ] Rewrite base-template.sh in Go (leave cli and install in sh)
- [ ] Make all existing bash tests (dont rewrite them) work and execute them with the `base-template` executable
- [ ] Rewrite `install.sh` (leave cli in sh) in Go
  - When a update is pulled, we compile the project (builds base-template,cli, install)  and dispatch to the compiled new install executable
  - The install then does the exact same as it does now.
  - Make all tests work with the new install executable.
- [ ] Rewrite cli.sh in Go
   - Make all tests work with the new cli executable.
 - etc ...

Files such as
- [ ] `.shared`,  `.trust` flags etc...
could be gathered in a YAML (or JSON) in `.githooks/config.yaml`

**Comment by rycus86** [comment]
I'm not super keen on the rewrite tbh, but happy to assist you if you want to try, then we can see how it's working out. You could also try to attack specific functions one-by-one, rather than replacing the whole base template runner in one go. Instead you could delegate execution to the new Go binary from the base template for things that are ready.

Having said this, I'm not super sure if the rewrite is worth the effort, so curious to understand more about the pain you're feeling with Shell?

**Comment by gabyx** [comment]
Jeah, if I would start a rewrite (more also out of curiosity) I should start only with good to tackle portions, like `base-temlate.sh` and test the tests which already directly use it :).

My pain:
- Pure shell is just too wobbly, its good for executable execution yes, but for scripting and logic and even small data structures such as list of strings. We use comma delimited strings, to mimic a list of strings... its not only dumb its also unsafe ... (e.g. URLs can contain ","  ;-))... 
- You can make local variables
- Performance is not really the problem so far
- Handling errors = some pain
- For certain list tasks you need to make a temporary file ... 🙈 
- a lot more I hate. I also got to know it much better with this project. Honstely, its pretty easy to understand but the fact that
- its totally not side effect free and functional as it look since we use global variables (which is sometimes a need) -> 🙈 
- Most of the code I think will get so clean and short in Go or even python, its sad to see that we have to make so stupid workaround sometimes... (e.g. legacy_transform function for local paths in shared hooks file `.shared`) -> 🙈

**Comment by gabyx** [comment]
As I am curious about go anyway, I make this project my test ground for *proper* go code :see_no_evil:.
https://github.com/gabyx/githooks/tree/feature/go-refactoring

**Comment by rycus86** [comment]
> As I am curious about go anyway, I make this project my test ground for _proper_ go code 🙈.
> https://github.com/gabyx/githooks/tree/feature/go-refactoring

Awesome! Looking forward to seeing what you get up to!
I can try to help if you need some help.

Also wanted to say that I have a few Go projects with Travis integration that could maybe help to get some ideas from:
- https://github.com/rycus86/ddexec this is a standalone binary uploaded to GitHub releases (then there's an install script to fetch the latest version)
- https://github.com/rycus86/container-metrics and https://github.com/rycus86/github-prometheus-exporter for example both have cross-compilation for other platforms (to run on things like Raspberry Pi for example), and they also have Docker + DockerHub publishing set up on Travis for them, though I guess that's less relevant here

**Comment by gabyx** [comment]
Sounds awesome, I already kind of love Go, some stuff is nicer in bash of course, but I think Go is the way to go.
See the latest, the code gets really clean :-) Currently triying to make some progress with runner.go... :-)

**Comment by gabyx** [comment]
![image](https://user-images.githubusercontent.com/647437/94625087-3a488000-02b8-11eb-99eb-415e9ce15f05.png)

**Comment by gabyx** [comment]
Coverage ist up, juheiii: https://coveralls.io/jobs/74453688

Not so bad with 78% so far.

**Comment by gabyx** [comment]
@rycus86: Checkout https://github.com/gabyx/githooks#dialog-tool :partying_face:
