### ISSUE TITLE
Direct link to cli is maybe not so good

### ISSUE THREAD

**Issue by gabyx** [rycus86/githooks#127]
I am thinking about reverting the direct use of the cli.sh from the release clone.
Since when anything happens (wrong branch specified `githooks.cloneBranch`) with an `git hooks update`.
The cli.sh is no more working since the whole release folder is not there anymore. =) 
A bit counterproductive...
Its rare that this happens, but if it happens its frustrating maybe....

**Comment by rycus86** [comment]
Sounds good, thanks!
