### ISSUE TITLE
Trust-all without confirmation?

### ISSUE THREAD

**Issue by gabyx** [rycus86/githooks#14]
Could we have a file `trust-all-noconfirm` File in the repo, such that after a `clone` and some actions on the repository the user does not need to confirm that the hooks are safe.
So completely setting `githooks.trust` to `Y`.

**Comment by rycus86** [comment]
See it here: https://github.com/rycus86/githooks#opt-in-hooks

> If the repository contains a `.githooks/trust-all` file, it is marked as a trusted repository. On the first interaction with hooks, Githooks will ask for confirmation that the user trusts all existing and future hooks in the repository, and if she does, no more confirmation prompts will be shown. This can be reverted by running either the `git config --unset githooks.trust.all`, or the `git hooks config reset trusted` command. This is a per-repository setting. These can be set up and changed with the [command line helper](https://github.com/rycus86/githooks/blob/master/docs/command-line-tool.md) tool as well, run `git hooks trust help` and `git hooks config help` for more information.

_tl;dr_: if you have a `.githooks/trust-all` file in the repo, it will only ask for confirmation once, then it will automatically accept all changes and new hooks.
If you're absolutely sure you want to trust those hooks, you can do so by executing `git config --local githooks.trust.all Y` in the repository after checkout. (I believe you can't run hooks straight after a `clone`)

**Comment by rycus86** [comment]
Are you OK to close this one?

**Comment by gabyx** [comment]
Ok, yes. This is probably an input which I wanted for non-interactive clones (from guis) maybe we can setup a dispatch tool which we can write such that all dialogues prompts go somewhere else. I open a PR for that :-) in such a way we can interact nicely with Git GUI's, of course this implementation is platform dependent. I will probably provide one for windows with powershell shizzle...
