### ISSUE TITLE
Install hooks in the curren folder `install.sh .`

### ISSUE THREAD

**Issue by sotte** [rycus86/githooks#2]
It would be great if one could install the hook in the current git repo with a simple `./install.sh .` or something.

**Comment by rycus86** [comment]
Hm, you mean, rather than installing it globally as templates, just install the hooks into a single repo?
That sounds like a good idea!

**Comment by sotte** [comment]
Yes, you have an existing project and just want to quickly add the hooks.

**Comment by rycus86** [comment]
This is now available after this commit: https://github.com/rycus86/githooks/commit/3974985588e2f2ed781eeb8e3119b8492b6fc81c

If you run either:

```shell
$ sh -c "$(curl -fsSL https://r.viktoradam.net/githooks)" -- --single
```

or 

```shell
$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/rycus86/githooks/master/install.sh)" -- --single
```

then it should only install the hooks into the current directory, and skip the global template setup.

Let me know how it works!

**Comment by sotte** [comment]
Thanks, works like a charm!
