### ISSUE TITLE
.ignore in shared repo not honored.

### ISSUE THREAD

**Issue by gabyx** [rycus86/githooks#21]
This is probably a new feature?
the .ignore in a shared repo is probably not honored right?

**Comment by rycus86** [comment]
The `.githooks/.ignore` file is applied to filenames of hooks in shared repos, but if the shared repo has a `.ignore` that is probably not matched. You could just remove the hook you don't need though.

**Comment by gabyx** [comment]
Thats true, so I cloise it. Thx :-)
