### ISSUE TITLE
Slow commit  and .githooks/README.md continuously recreated

### ISSUE THREAD

**Issue by brandonkal** [rycus86/githooks#24]
As the title says, there are times when a git commit becomes unbearably slow. The .githooks/README.md will appear. I don't really want to commit this to the repo, especially those that I contribute to that do not use githooks.

It seems like something must be causing githooks to continually reset a repo at times.

**Comment by rycus86** [comment]
Hm, that sounds bad. Do you know any way of reproducing it?

**Comment by brandonkal** [comment]
I am not sure how to reproduce this.

**Comment by gabyx** [comment]
when is the Readme recreated? Do you know the source @rycus86 ? Is there a setting in the config which recreates the readme?

**Comment by rycus86** [comment]
There's a `git hooks readme add|update` command on the cli tool, but nothing that would recreate it during actual hook executions. The install script offers to create README files, but it should ask for confirmation, and also doesn't happen when executing hooks.

**Comment by rycus86** [comment]
Closing this for now, but feel free to reopen it if you manage to work out how to reproduce it! Thanks!
