### ISSUE TITLE
Bug: Git leaking env variables in hooks!

### ISSUE THREAD

**Issue by gabyx** [rycus86/githooks#25]
By the answer:
https://stackoverflow.com/a/57021451/293195
of the maintainer of pre-commit. Git has some problems, this project should also take of these side effects, by trying maybe to execute git command in `base-template.sh` without environment variables set. How should we incorporate this knowledge, I also found this bug for PR #22 .

**Comment by rycus86** [comment]
Thanks for bringing this to my attention! I'll have a look, weird that it hasn't caused any issues so far.
