### ISSUE TITLE
Automatically create .githooks folder and README on install 

### ISSUE THREAD

**Issue by sotte** [rycus86/githooks#3]
When installing githooks, maybe you should also create a `.githooks` folder and a `.githooks/README.md` that explains a a bit how githooks works. (At least that is what I'm doing for some projects.)

**Comment by rycus86** [comment]
That's a good idea! I was thinking about this, just wasn't sure whether people would consider this intrusive to their repos. It would certainly help having some explanation in the repo, just not sure whether it would be more useful than annoying? :)

What are your thoughts on this?

**Comment by sotte** [comment]
My thought was something like this: After installing githook nothing really changed in the repo, `git status` is clean. Did anything happen at all? I've read the docs and I know that `.git/hooks/` was updated and that I have to create a `.githook` folder and folders for each hook that I want to use. I would have to do that for every project. Now there is a .githook folder but other ppl. that don't know about the githook project are just confused. Don't hooks live in .git/hooks?

So having a `.githook/README.md` that gives a TLDR of the githooks project and how you can create your own hooks (maybe a list of all available hooks? maybe just a link) would be great (and save me from adding it to every single repo :) ).

**Comment by rycus86** [comment]
@sotte what do you think of the contents here: https://github.com/rycus86/githooks/blob/wip-included-readme/.githooks/README.md ?

**Comment by rycus86** [comment]
This is now implemented in https://github.com/rycus86/githooks/commit/5fafb31559d1f3741618769f0daa8b060d07f2e0 :tada: 

Let me know if you have any comments/suggestions about it!

And thanks a lot for taking the time to suggest new features! :)
