### ISSUE TITLE
Make errors all go to stderr instead of stdout.

### ISSUE THREAD

**Issue by gabyx** [rycus86/githooks#33]
Wouldnt it make sense to stream all errors to stderr instead of stdout? 
I can prepare some simple PR for this, if you like.

**Comment by rycus86** [comment]
In general, maybe yes. What examples do you have in mind?
My only concern would be output and error messages getting mixed up on the terminal when printing. :/

**Comment by gabyx** [comment]
why? should they get mixed up (ok the tests will fail, and have to be adapted)? Isn't any cli tool adhering to these rules, err -> stderr, output ->stdout?
See #34

**Comment by rycus86** [comment]
Can you please just let me know on both PRs when you finished with them and are ready for another review? Thanks a lot!

**Comment by gabyx** [comment]
I made all changes. Do not have time anymore today. If you like, pull them, make the corrections needed and directly merge back :-), adapted one test for the readme thats all :-)
Thx! have a good weekend!


> On 03 Aug 2019, at 14:54, Viktor Adam <notifications@github.com> wrote:
> 
> 
> You are receiving this because you authored the thread.

Gabriel Nützi
MSc ETH Mechanical Engineering

gnuetzi@gmail.com
+41 (0) 77 424 86 45

**Comment by rycus86** [comment]
Thanks a lot! I think I'll also leave it for tonight, will try to merge it in tomorrow. Have a good weekend too!
