### ISSUE TITLE
Disable githook when pull/cloning shared hook repos

### ISSUE THREAD

**Issue by gabyx** [rycus86/githooks#37]
Can we somehow disable githooks in `update_shared_hooks_in`  ?
Because when I ran
`git hooks update shared` it cloned the shared repo and executed the hook `post-checkout` which failed... Do we really want to let githooks also run when pulling shared hook repos?
Can we override the  template dir maybe to an non existing path in `update_shared_hooks_in`?

**Comment by rycus86** [comment]
I think there's a flag on `git clone` to not run `post-checkout`, let me see.

**Comment by gabyx** [comment]
also on pull?

**Comment by rycus86** [comment]
https://git-scm.com/docs/githooks#_post_checkout

There's `--no-checkout` for clone, but well still need to do later, though this hook can't fail the `pull`.

Why are you getting failures, maybe those shared hooks should be shared differently? Just wondering about your setup/layout.

**Comment by gabyx** [comment]
Hm... maybe its better to let githooks also run there, what do you think...?
I mean if you checkout the shared hook repo and it does not work because of a failing post-checkout
something is anyway wrong with tje hook it-self.  The error arose because I still had post-checkout lfs hook (which failed because it needed something irrelevant (python)) in the shared repo...
I think we should not change anything here. The shared hook repo is a git repo, and when cloned githooks does its things...

**Comment by rycus86** [comment]
Yeah, I agree.
Those shared hooks need to be a bit more careful because you don't know what repo do they get used with.

Alternatively, if you put the shared repo in a repo's `.shared` file (I think, on mobile) then it should use the shared repo with that repo only (and others that use the same one). Does that make sense?

**Comment by gabyx** [comment]
Jeah, makes sense :-). Especially about carefullness.

**Comment by rycus86** [comment]
Should we close this issue then?
