### ISSUE TITLE
How do shared git hooks get updated?

### ISSUE THREAD

**Issue by bjbishop** [rycus86/githooks#4]
Hi, great project!  Thanks for sharing this.  I'm switching over to this from pre-commit.com.

Questions on shared hooks:

I've got a shared hooks repository set up and I've made it global in my .gitconfig.  The first time I'm using them within other git repos, the shared hooks work great.

I've since made updates to my shared pre-commit hook but doing git commits in my other projects don't seem to be getting the newest version?  They're still executing my original version of the shared hook.

I see this in the code in order to trigger an update of the shared hooks manually but I don't know where to create that `.githooks.shared.trigger` file.

```sh
    # run an init/update if we are after a "git pull" or triggered manually
    if [ "$HOOK_NAME" = "post-merge" ] || [ "$HOOK_NAME" = ".githooks.shared.trigger" ]; then
```

Thanks again!

**Comment by rycus86** [comment]
Hi,

Thanks a lot for trying the project!
The `.githooks.shared.trigger` is just a trick really to force the shared repo update during running the install script.

Other condition there, for the [post-merge](https://git-scm.com/docs/githooks#_post_merge) should run on `git pull`.
Is that not the case?
I'm not sure I've tested whether the hook is triggered when there are no updates as a result of the pull.

Let me know if this helps!

Thanks you!

**Comment by bjbishop** [comment]
Wow, thanks for the quick response!

When I did the installation, I had it update all my existing repos in my `~/src` dir, and it seems like they're all using the shared hooks repo just fine.  So I thought that going into any one of my other projects in `~/src` and doing a `git pull` would update my shared hooks but it doesn't seem to be.  I've tried many repos that I've got and so far the shared githooks haven't been updated yet.

How can I help?  Here are some versions that might be useful

`Mac OS 10.12.6`

Installed from homebrew:
`git version 2.18.0`
`bash version 4.4.23`

**Comment by rycus86** [comment]
Could you try adding a `.githooks/post-merge/test` file, with some content like `echo "Running this hook"`, then do a `git pull`?
You shouldn't need to commit it, just having it there should trigger it I think.

Can you see that printing the test message?

Thanks!

**Comment by bjbishop** [comment]
Aha!  That did it!

Maybe post-merge doesn't run as a hook if there were no changes to pull down?  I was pulling from repositories before that I knew had changes from upstream, but none of those repos have anything in their .githooks directory except the README.md, since I wanted everything to use my global shared hooks.

Seems like that did it now when I added that post-merge hook in!

```sh
~/src/chef/darth$  [tsk:6a9c] mkdir -p .githooks/post-merge                                                                                                  
~/src/chef/darth$  [tsk:6a9c] echo "echo 'Testing'" > .githooks/post-merge/test                                                                              
~/src/chef/darth$  [tsk:6a9c] chmod a+x .githooks/post-merge/test                                                                                            
~/src/chef/darth$  [tsk:6a9c] .githooks/post-merge/test
Testing
~/src/chef/darth$  [tsk:6a9c] git pull
remote: Counting objects: 264, done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 264 (delta 192), reused 239 (delta 170)
Receiving objects: 100% (264/264), 46.12 KiB | 162.00 KiB/s, done.
Resolving deltas: 100% (192/192), done.
...
...
* Updating shared hooks from: git@gilligan.pearsondev.com:BISHBR/shared-git-hooks.git
? New hook file found: /Users/bishbr/src/chef/darth/.githooks/post-merge/test
  Do you you accept the changes? (Yes, all, no, disable) [Y/a/n/d] a
Testing
~/src/chef/darth$  [tsk:6a9c] 
```

**Comment by rycus86** [comment]
Great, thanks! This might make it easier to figure out a solution. I'll try to have a look tomorrow to see if there's a better way of doing this.

Thanks again!

PS: you can omit the `chmod a+x` if you'd like for Shell scripts, non-executable files will be run through `sh <hook-file>` :)

**Comment by rycus86** [comment]
Hi @bjbishop ,

Looking through https://git-scm.com/docs/githooks, I'm not sure which hooks should trigger a shared repo update without making the user experience bad with too frequent `pull`s for example.
The `post-merge` sort of makes sense, as you're already doing a `pull` anyway.

I think I'll approach this from a different angle: perhaps a locally installed helper script, which could help you do something like `githooks update-shared` or similar. This could help a bit while developing the hooks in the shared repo and testing them locally.

What do you think?

**Comment by bjbishop** [comment]
:+1: I think the helper script would be good, so I can have my team run a script to force the updating of the shared hooks repo.  Thanks again for your help!

**Comment by rycus86** [comment]
I made a start on the cli script, just have a bit of docs and installing to sort out: https://raw.githubusercontent.com/rycus86/githooks/wip-cli/cli.sh

Would you like to give it a test? If you do, some feedback on it would be much appreciated!
You can try it like this:

```shell
$ curl -fsSL https://raw.githubusercontent.com/rycus86/githooks/wip-cli/cli.sh > githooks
$ chmod a+x githooks
$ ./githooks help
```

Thanks!

**Comment by bjbishop** [comment]
Thank you!  That script is working great and it is pulling down and updating my shared hooks.  I'll keep playing with it and let you know if I've got any more feedback on it.  Thanks again Viktor!

**Comment by rycus86** [comment]
Thanks! 😊
That's a good idea! I'll add it, then try to wrap up the cli script into the master branch in the next few days.

**Comment by rycus86** [comment]
Hi @bjbishop ,

Thanks a lot again for the great suggestions! This is now ready on `master`.
Just run `git hooks help` after updating to see the options, or check them here: https://github.com/rycus86/githooks/blob/master/docs/command-line-tool.md

Thanks!
