### ISSUE TITLE
Compatibility Questions

### ISSUE THREAD

**Issue by brandonkal** [rycus86/githooks#5]
I really appreciate the simple solution this project provides! I looked at pre-commit.com and in comparison it is an overly complex solution to a simple problem.

This looks like the perfect fit for most projects.

I also like the streamlined nature of husky for node projects.

Have you tested this for compatibility with pre-commit and husky?
Since these are popular with open source projects, I wonder if they would be incompatible.

Since `pre-commit install` is run after `git clone`, it seems it would overwrite any git hook templates used by githooks.

Also, is it possible to use personal global githooks? I could see this as useful for simple things like spell checking commit messages.

Also, how does this work with checking only staged files, or partially staged files (which is currently a pain point for lint-staged project).

**Comment by rycus86** [comment]
Hi @brandonkal ,

> I really appreciate the simple solution this project provides! I looked at pre-commit.com and in comparison it is an overly complex solution to a simple problem.
> 
> This looks like the perfect fit for most projects.

Thanks for the kind words, really! :)

> I also like the streamlined nature of husky for node projects.
> 
> Have you tested this for compatibility with pre-commit and husky?
> Since these are popular with open source projects, I wonder if they would be incompatible.

I haven't tried them to be honest. Githooks is trying to be language/framework agnostic, though I can see the benefit of having a solution, like husky, that targets Node and integrates well with the project declaration, etc.
If there would be any compatibility, what would make sense do you think? Would you have any use-cases or examples?

> Since `pre-commit install` is run after `git clone`, it seems it would overwrite any git hook templates used by githooks.

Yes, that is true, it would overwrite them. At that point, I wouldn't be able to prevent or change that, unless I open a PR against those projects to add support for recognising my hooks and scripts.

> Also, is it possible to use personal global githooks? I could see this as useful for simple things like spell checking commit messages.

Yes, absolutely! You can use [shared hook repos](https://github.com/rycus86/githooks#shared-hook-repositories), and configure them as __global__ shared repos, with `git hooks shared add --global git://my/repo.git`, see the docs here: https://github.com/rycus86/githooks/blob/master/docs/command-line-tool.md#git-hooks-shared
This will put these on a global git config with the `githooks.shared` key, then any hooks in these shared repos will be applied across all your projects on that machine.
The __local__ shared hook repos, in contrast, are listed in the `.githooks/.shared` file, and are expected to be shared with all the collaborators on the project.
Let me know if you need more clarification on this, not sure if I managed to explain it well.

> Also, how does this work with checking only staged files, or partially staged files (which is currently a pain point for lint-staged project).

We have managed to work this out quite well at work, I think it was something like this:

1. Get the list of added/modified files for the current commit with `git diff --name-only --diff-filter=AM | grep '.java'`
2. Run the linter with the list of files passed in as parameters, like `java -jar checkstyle.jar ${CHANGED_FILES}`

Does this help?

**Comment by brandonkal** [comment]
Yes, these answers help a lot. For compatibility, I imagine running githooks after the linters defined by pre-commit. Personally, I don't imagine using pre-commit myself, but it would be nice to have global hooks run on those projects if I end up forking a project that relies on it.

Perhaps add a one-off CLI command to add global hooks to a project? It would have to copy in the githooks template under a different name. The command would also add a pre-commit a local linter in the yaml file to execute the githooks after pre-commit. A similar approach could probably work for husky.

**Comment by brandonkal** [comment]
Thank you for the pointers on how to check only staged files.
This seems best:
```
git diff-index --cached --diff-filter=AM --no-renames HEAD
```

Would it be possible to add this as part of the template directly? I believe this would be a great feature to have the template create a ${CHANGED_FILES} variable that can then be passed to the executables called. This would simplify my pre-commit scripts.

**Comment by brandonkal** [comment]
Yes, I suppose CHANGED_FILES can vary a lot. My initial thought was just to export all changed files and then pipe that into grep in each script. But for looking only in one folder, there is the option to use --relative which will of course vary a lot between projects. i.e.:
```
git diff-index --cached --diff-filter=AMR --name-only --relative=ansible HEAD
```
Which I found myself writing for running an ansible linter if something thanged in the project's ansible directory.

So leaving it out for the flexibility would be nice, but it did seem a bit odd writing that out for every script in the `.githooks/pre-commit/` folder.

**Comment by rycus86** [comment]
Hi @brandonkal ,

I'm still not sure what to do about the `CHANGED_FILES`. While it sounds pretty common to only check the changed files, I think the definition of what's changed will differ from one project to another.
Within a single repo though, you could have a single script that `export`s the variable according to rules that is appropriate for the repo, and just execute it with a one-liner from each of the actual hook scripts.
I could add support for *something* like this into Githooks, but the projects would probably still have to define how they want to assemble the list of changes, so it's about the same amount of changes per-repo.

Is there maybe something I'm missing? Do you have any suggestions for this, or should I just close this otherwise?

Thanks!

**Comment by brandonkal** [comment]
A resonable approach would be to decide on a generic definition of `CHANGED_FILES`. Of course, this variable could be easily overriden by any bash script called by githooks.

**Comment by rycus86** [comment]
Do you have suggestions on what the definition should be?
I'm struggling to find something that is generic enough to be useful across many projects, while not having to change it in almost all of them, because it is too generic. :)

**Comment by brandonkal** [comment]
Something like this should be generic enough:
A better variable name for this would be `STAGED` instead of `CHANGED_FILES`

```
git diff-index --cached --diff-filter=ACMR --name-only HEAD
```

Basically, show me staged files added, copied, modified, or renamed.

Alternatively a blacklist approach could be used:
```
git diff-index --cached --diff-filter=duxb --name-only HEAD
```
Basically, show me staged files not deleted, unmerged, unknown, or broken.

**Comment by rycus86** [comment]
OK, sounds sensible, I can give it a go.
Would `git diff` be just as good as `git diff-index` ?
It seems like the former is less likely to trip up:

```shell
$ git diff --cached --diff-filter=ACMR --name-only HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
$ echo $?
128
```

```shell
$ git diff --cached --diff-filter=ACMR --name-only 
$ echo $?
0
```

**Comment by brandonkal** [comment]
Even better, as it looks cleaner. And HEAD can be left out since it is the default

**Comment by rycus86** [comment]
Hm... I was just about to commit the change for this.
But I was wondering, does this make sense for any hooks apart from `*commit*` ?

**Comment by brandonkal** [comment]
Perhaps for the various msg hooks.

**Comment by rycus86** [comment]
Yeah, looks like `pre-commit`, `prepare-commit-msg` and `commit-msg` will see the changes, `post-commit` will get an empty list.
Not sure if the "staged changes" makes sense on any of the other hooks?

```
    applypatch-msg pre-applypatch post-applypatch
    pre-commit prepare-commit-msg commit-msg post-commit
    pre-rebase post-checkout post-merge pre-push
    pre-receive update post-receive post-update
    push-to-checkout pre-auto-gc post-rewrite sendemail-validate
```

**Comment by rycus86** [comment]
OK, https://github.com/rycus86/githooks/commit/2efbdcbd1555bba06096b959931ae8011640a462 adds this now.
Would be great if you could give it a test and let me know how it goes? :)

Thank you!

**Comment by brandonkal** [comment]
In my initial testing, this did not work, perhaps because the export is not available in a subshell.

My original pre-commit file:
```
#!/bin/bash

CHANGED_FILES=$(git diff-index --cached --diff-filter=AM --no-renames --name-only HEAD | grep .php$ )

if [[ -n $CHANGED_FILES ]]; then
    # shellcheck disable=SC2086
    vendor/bin/phpcs --basepath="public/app" --no-colors $CHANGED_FILES
```

After updating:
```
#!/bin/bash

CHANGED_FILES=$($STAGED_FILES | grep .php$ )

if [[ -n $CHANGED_FILES ]]; then
    # shellcheck disable=SC2086
    vendor/bin/phpcs --basepath="public/app" --no-colors $CHANGED_FILES
fi
```
I tested by making a bad.php file with invalid syntax. With the second approach, the commit was allowed through.

Perhaps a better approach would be to make it a `git-hooks` command. Though at this point I wonder if this shortcut was even worth it.

Something like:
git hooks staged
is a function for:
git diff --cached --diff-filter=ACMR --name-only

**Comment by rycus86** [comment]
Hm... Was this exactly your hook? Looks like there's an `echo` missing:

```
CHANGED_FILES=$(echo "$STAGED_FILES" | grep .php$ )
```

Can you try this way?

**Comment by brandonkal** [comment]
Good catch! After fixing that error it still failed.

I even tried this to verify everything was working:
```
CHANGED_FILES=$(echo "$STAGED_FILES" | grep .php$)

if [[ -n $CHANGED_FILES ]]; then
    echo "$CHANGED_FILES"
    exit 1
    # shellcheck disable=SC2086
    vendor/bin/phpcs --basepath="public/app" --no-colors $CHANGED_FILES
fi
```
That worked. It aborted the commit and the output was as expected:
```
public/app/bad.php
```
But yet, phpcs is not functioning this way when I remove the `exit 1` I used to debug.

**Comment by rycus86** [comment]
Is `phpcs` a linter? If yes, and you want the commit to fail when it fails, you might need to do:

```
if ! vendor/bin/phpcs --basepath="public/app" --no-colors $CHANGED_FILES; then
  exit 1
fi
```

Or otherwise set a Bash flag I don't know off the top of my head, that fails the script when any of the lines fail.

**Comment by brandonkal** [comment]
It's not public but I'll see about making a little demo repo to see if it is reproducible.

**Comment by rycus86** [comment]
That would be awesome, thanks!

**Comment by brandonkal** [comment]
@rycus86 

Here it is. With this repo I cannot reproduce the issue. So it must be something to do with the update process as this fresh repo seems to work just fine 👍 

https://github.com/brandonkal/githooks-demo

**Comment by rycus86** [comment]
Thanks for that! Yeah, it seems to fail as expected, still not sure though why the `phpcs` failure comes through automatically, but OK.
In your original repo, you could try adding a `set -x` to the top of your hook after the shebang, then it will print out the commands it executes, including the value it sets for the variables.
Maybe that would help resolving the issue with that one?

**Comment by rycus86** [comment]
Hey @brandonkal , is there anything left to do on this issue, or can it be closed?

**Comment by brandonkal** [comment]
Yes, let's close it. Thanks!
