### ISSUE TITLE
Break recursion occuring with shared repos

### ISSUE THREAD

**Issue by gabyx** [rycus86/githooks#50]
We need to consider the following
When you `git hooks shared update` in a local repo and it downloads the repo into `~/.githooks/shared/hookrepo`
During any `git pull` which happens in this shared hook checkout folder, since it contains an `.githooks` folder and `.git/hooks` is setup with the githook manager:
any `post-merge` hook will be executed since it reacts to `git pull`.

To break this recursion, we should skip executing any hook.
Solution: 
- stop in the `base-template.sh` when the `$(pwd)` is in a shared hook checkout [hack]
- or `git hooks uninstall` after any checkout of these shared hooks [stupid overhead]
- or `git clone --template="" $url ~/.githooks/shared/hookrepo` and afterwards if LFS is available
`git lfs install --local` [best ?]

**Comment by rycus86** [comment]
https://github.com/typicode/husky/issues/206#issuecomment-471169193

Maybe that's a cheaper option to implement -- `git -c core.hooksPath /dev/null pull`

**Comment by gabyx** [comment]
Fixed with `env -i`. I close this.
