### ISSUE TITLE
Install only server hooks if bare

### ISSUE THREAD

**Issue by gabyx** [rycus86/githooks#63]
Can we add another small feature, that we only install server hooks 
- pre-receive
- update
- post-receive

If the repo is bare: We already have a variable detecting this :

```
IS_BARE=$(cd "${TARGET}" && git rev-parse --is-bare-repository 2>/dev/null)
```

in every install. So we select the appropriate hooks to loop over...

**Comment by rycus86** [comment]
Yeah, that makes sense to me. Are these 3 the only ones that make sense? Any more hook types to include?

**Comment by gabyx** [comment]
No I have to investigate, its more
```
MANAGED_SERVER_HOOK_NAMES="
    pre-receive update post-receive post-update
    push-to-checkout pre-auto-gc
"
```

**Comment by gabyx** [comment]
https://stackoverflow.com/questions/58972724/what-all-git-hooks-can-be-called-in-a-bare-repository

**Comment by rycus86** [comment]
Thanks for investigating!

**Comment by rycus86** [comment]
This is already merged.
