### ISSUE TITLE
Behavior of git hooks config set disable

### ISSUE THREAD

**Issue by gabyx** [rycus86/githooks#73]
why should `git hooks config set disable` in a repository disable excuting any `xxxx.replaced.*` hooks
and execute nothing?
We already execute LFS Hooks (because failure to do so, has bad consequences...).
Shouldn't we adopt the same behavior as if githooks is not installed in the repository...??

**Comment by gabyx** [comment]
See #74

**Comment by rycus86** [comment]
Yep, makes sense. Thank you!
