### ISSUE TITLE
Install fails in Linux with `bash: /usr/bin/sh: Argument list too long`

### ISSUE THREAD

**Issue by obonyojimmy** [rycus86/githooks#80]
OS: Ubuntu Linux 19.01

Running install script `sh -c "$(curl -fsSL https://raw.githubusercontent.com/rycus86/githooks/master/install.sh)"` fails with error 

_bash: /usr/bin/sh: Argument list too long_

**Comment by rycus86** [comment]
Thanks for reporting! I'll have a look.
In the meantime, you should be able to download and run the install script, for example:
```
curl -fsSL https://raw.githubusercontent.com/rycus86/githooks/master/install.sh -o githooks-install.sh && sh githooks-install.sh
```

**Comment by obonyojimmy** [comment]
works when piped to shell executor `source <(curl -fsSL https://r.viktoradam.net/githooks)`
