### ISSUE TITLE
git-worktree not supported

### ISSUE THREAD

**Issue by cscutcher** [rycus86/githooks#9]
Git worktree seems to be unsupported across the board. This is a real pain for me at the moment as I'm having to work with a few active worktrees on my current project.

### Symptoms

For example;

```sh
> git hooks list
The current directory (/home/user/git/worktree-repo) does not seem to be the root of a Git repository!
```

Presumably this is because in a git worktree the `.git` path is not a directory but a file containing something like this;
```
gitdir: /home/user/git/real-repo
```
where `/home/user/git/real-repo` is the "real" git repo. The check in `is_running_in_git_repo_root()`;

```sh
[ -d .git ] || return 1
```

fails as a result.

Trusting a new hook also fails;

```
? New hook file found: /home/user/git/worktree-repo/.githooks/pre-commit/00-isort
  Do you you accept the changes? (Yes, all, no, disable) [Y/a/n/d] Y
/home/user/git/real-repo/.git/hooks/pre-commit: line 324: .git/.githooks.checksum: Not a directory
```

This also seems to be due to trouble discovering the "real" git config directory. 

### Potential fix

A potential fix would be to replace references to `.git` with the result of `git rev-parse --git-common-dir` which seems to return the path to the `.git` dir of the "real" repo, but I'm not sure if there would be other ramifications.

**Comment by rycus86** [comment]
Thanks a lot for reporting this!

I haven't used worktrees, but can look into this to see where I'd need to change the code to add support for them.
Could you perhaps give me a list of commands or steps to setup a minimal example I could see this failing on?
I can look it up, just thought it might be faster this way. :)

Thanks!

**Comment by cscutcher** [comment]
Created this asciinema cast of the bug with some experimentation with the various invocations of `git rev-parse` which might be helpful. 

[![asciicast](https://asciinema.org/a/Au2aLbSAILBmWZn8qbtJDuAv9.svg)](https://asciinema.org/a/Au2aLbSAILBmWZn8qbtJDuAv9)

In case you're not familiar with asciinema it's possible to fast forward and pause at any point which is useful given that I keep pausing to work out what I'm going to do :-p . You can also copy and paste from the cast if you want to try the commands yourself which is handy.

Annoyingly I forgot to run `git hooks list` but you can see the failure occuring on commit. 

Let me know if there's anything else I can do to help. I think it should be as simple as replacing references to the `.git` dir with the result of `git rev-parse --git-common-dir` but that's just on a quick scan of the code so I could be way off. If you want to be cautious you might want to do a check up front to see if we're in a `git-worktree` and revert to assuming the `.git` dir otherwise, that would make sure that anyone not using `git-worktree` should be unaffected, but on the otherhand it seems pretty safe to use `git rev-parse --git-common-dir`. 

Oh I forgot to share the version of git I'm using; `git version 2.20.1`

**Comment by rycus86** [comment]
Thanks again for this!

I went with your suggestion and used the common dir as a base. https://github.com/rycus86/githooks/commit/04800a8bbde79044bce3cc123924891ac1eb1be6 should have this now, if you just do an update, it should work.

Let me know if this solves the problems for you!

Thanks!

**Comment by cscutcher** [comment]
That seems have fixed it! Thanks a bunch for fixing it so quickly! I'm not sure if you prefer to click close issue yourself, but I'm happy for issue to be closed.
